// <auto-generated />
using System;
using LinkIndia.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace LinkIndia.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20210908144405_IntialCreate")]
    partial class IntialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 64)
                .HasAnnotation("ProductVersion", "5.0.9");

            modelBuilder.Entity("LinkIndia.Model.TransporterReg", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Add_Line1")
                        .HasColumnType("text");

                    b.Property<string>("Add_Line2")
                        .HasColumnType("text");

                    b.Property<byte[]>("AddressProof")
                        .HasColumnType("varbinary(4000)");

                    b.Property<byte[]>("BusinessAddressProof")
                        .HasColumnType("varbinary(4000)");

                    b.Property<string>("City")
                        .HasColumnType("text");

                    b.Property<string>("District")
                        .HasColumnType("text");

                    b.Property<string>("FirstName")
                        .HasColumnType("text");

                    b.Property<string>("LastName")
                        .HasColumnType("text");

                    b.Property<string>("Mobile")
                        .HasColumnType("text");

                    b.Property<byte[]>("Pancard")
                        .HasColumnType("varbinary(4000)");

                    b.Property<byte[]>("Selfie")
                        .HasColumnType("varbinary(4000)");

                    b.Property<string>("State")
                        .HasColumnType("text");

                    b.Property<string>("TransportName")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("transporterRegs");
                });
#pragma warning restore 612, 618
        }
    }
}
