// <auto-generated />
using System;
using LinkIndia.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace LinkIndia.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20210920062937_trukTypeCoumn")]
    partial class trukTypeCoumn
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 64)
                .HasAnnotation("ProductVersion", "5.0.9");

            modelBuilder.Entity("LinkIndia.Models.Client_LoadReg", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Add_Line1")
                        .HasColumnType("text");

                    b.Property<string>("Add_Line2")
                        .HasColumnType("text");

                    b.Property<byte[]>("AddressProof")
                        .HasColumnType("varbinary(4000)");

                    b.Property<byte[]>("BusinessAddressProof")
                        .HasColumnType("varbinary(4000)");

                    b.Property<string>("City")
                        .HasColumnType("text");

                    b.Property<string>("District")
                        .HasColumnType("text");

                    b.Property<string>("FirstName")
                        .HasColumnType("text");

                    b.Property<string>("LastName")
                        .HasColumnType("text");

                    b.Property<string>("Mobile")
                        .HasColumnType("text");

                    b.Property<byte[]>("Pancard")
                        .HasColumnType("varbinary(4000)");

                    b.Property<byte[]>("Selfie")
                        .HasColumnType("varbinary(4000)");

                    b.Property<string>("State")
                        .HasColumnType("text");

                    b.Property<string>("TransportName")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("client_LoadRegs");
                });

            modelBuilder.Entity("LinkIndia.Models.PostLoad", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime");

                    b.Property<string>("LoadFrom")
                        .HasColumnType("text");

                    b.Property<string>("LoadTo")
                        .HasColumnType("text");

                    b.Property<string>("MaterialType")
                        .HasColumnType("text");

                    b.Property<string>("Mobile")
                        .HasColumnType("text");

                    b.Property<int>("NumberOfTrucks")
                        .HasColumnType("int");

                    b.Property<string>("TruckCapacity")
                        .HasColumnType("text");

                    b.Property<int>("TruckSubType")
                        .HasColumnType("int");

                    b.Property<int>("TruckType")
                        .HasColumnType("int");

                    b.Property<float>("Weight")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.ToTable("postLoads");
                });

            modelBuilder.Entity("LinkIndia.Models.PostTruck", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("AddharNumber")
                        .HasColumnType("text");

                    b.Property<string>("Mobile")
                        .HasColumnType("text");

                    b.Property<string>("OwnerName")
                        .HasColumnType("text");

                    b.Property<byte[]>("RCBack")
                        .HasColumnType("varbinary(4000)");

                    b.Property<byte[]>("RCFront")
                        .HasColumnType("varbinary(4000)");

                    b.Property<string>("RouteFrom")
                        .HasColumnType("text");

                    b.Property<string>("State")
                        .HasColumnType("text");

                    b.Property<int>("TruckSubTypeId")
                        .HasColumnType("int");

                    b.Property<int>("TruckTypeId")
                        .HasColumnType("int");

                    b.Property<string>("VehicleNumber")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("postTrucks");
                });

            modelBuilder.Entity("LinkIndia.Models.TransporterReg", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Add_Line1")
                        .HasColumnType("text");

                    b.Property<string>("Add_Line2")
                        .HasColumnType("text");

                    b.Property<byte[]>("AddressProof")
                        .HasColumnType("varbinary(4000)");

                    b.Property<byte[]>("BusinessAddressProof")
                        .HasColumnType("varbinary(4000)");

                    b.Property<string>("City")
                        .HasColumnType("text");

                    b.Property<string>("District")
                        .HasColumnType("text");

                    b.Property<string>("FirstName")
                        .HasColumnType("text");

                    b.Property<string>("LastName")
                        .HasColumnType("text");

                    b.Property<string>("Mobile")
                        .HasColumnType("text");

                    b.Property<byte[]>("Pancard")
                        .HasColumnType("varbinary(4000)");

                    b.Property<byte[]>("Selfie")
                        .HasColumnType("varbinary(4000)");

                    b.Property<string>("State")
                        .HasColumnType("text");

                    b.Property<string>("TransportName")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("transporterRegs");
                });

            modelBuilder.Entity("LinkIndia.Models.TruckOwnerReg", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Add_Line1")
                        .HasColumnType("text");

                    b.Property<string>("Add_Line2")
                        .HasColumnType("text");

                    b.Property<byte[]>("AddressProof")
                        .HasColumnType("varbinary(4000)");

                    b.Property<byte[]>("BusinessAddressProof")
                        .HasColumnType("varbinary(4000)");

                    b.Property<string>("City")
                        .HasColumnType("text");

                    b.Property<string>("District")
                        .HasColumnType("text");

                    b.Property<string>("FirstName")
                        .HasColumnType("text");

                    b.Property<string>("LastName")
                        .HasColumnType("text");

                    b.Property<string>("Mobile")
                        .HasColumnType("text");

                    b.Property<byte[]>("Pancard")
                        .HasColumnType("varbinary(4000)");

                    b.Property<byte[]>("Selfie")
                        .HasColumnType("varbinary(4000)");

                    b.Property<string>("State")
                        .HasColumnType("text");

                    b.Property<string>("TransportName")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("truckOwnerRegs");
                });

            modelBuilder.Entity("LinkIndia.Models.TruckSubTypes", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("SubType")
                        .HasColumnType("text");

                    b.Property<int?>("TruckTypeId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("TruckTypeId");

                    b.ToTable("trucksubTypes");
                });

            modelBuilder.Entity("LinkIndia.Models.TruckType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Type")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("truckTypes");
                });

            modelBuilder.Entity("LinkIndia.Models.TruckSubTypes", b =>
                {
                    b.HasOne("LinkIndia.Models.TruckType", "TruckType")
                        .WithMany()
                        .HasForeignKey("TruckTypeId");

                    b.Navigation("TruckType");
                });
#pragma warning restore 612, 618
        }
    }
}
